export type KolkapPlanKey = "free_trial" | "growth" | "pro" | "business";

export type KolkapCreditRule = {
  label: string;
  credits: number;
  description: string;
};

export type KolkapTopUpPackage = {
  id: string;
  priceUsd: number;
  credits: number;
};

export type KolkapPlan = {
  key: KolkapPlanKey;
  name: string;
  priceLabel: string;
  monthlyPriceUsd: number | null;
  aiStaffLimit: number | "custom";
  monthlyCredits: number | "custom";
  trialDays?: number;
  description: string;
  features: string[];
};

export type KolkapWorkspacePlanStatus = {
  businessName: string;
  planKey: KolkapPlanKey;
  planName: string;
  status: "trial" | "active" | "past_due" | "cancelled";
  trialDaysRemaining: number;
  creditsTotal: number;
  creditsUsed: number;
  creditsRemaining: number;
  aiStaffLimit: number | "custom";
  aiStaffUsed: number;
  whatsappStatus: "not_connected" | "connected" | "pending";
  goLiveStatus: "draft" | "testing" | "live";
};

export const kolkapPlans: Record<KolkapPlanKey, KolkapPlan> = {
  free_trial: {
    key: "free_trial",
    name: "Free Trial",
    priceLabel: "Free",
    monthlyPriceUsd: 0,
    aiStaffLimit: 1,
    monthlyCredits: 100,
    trialDays: 14,
    description: "Test Kolkap before choosing a paid plan.",
    features: [
      "14 days free",
      "100 AI credits",
      "1 AI staff",
      "Create AI flow",
      "Add business knowledge",
      "Test AI replies",
    ],
  },

  growth: {
    key: "growth",
    name: "Growth",
    priceLabel: "$49.99/month",
    monthlyPriceUsd: 49.99,
    aiStaffLimit: 2,
    monthlyCredits: 1500,
    description: "For small businesses ready to use AI for replies and leads.",
    features: [
      "2 AI staff",
      "1,500 AI credits/month",
      "WhatsApp setup flow",
      "Inbox and leads",
      "Human handover",
      "Social media caption generator",
    ],
  },

  pro: {
    key: "pro",
    name: "Pro",
    priceLabel: "$99.00/month",
    monthlyPriceUsd: 99,
    aiStaffLimit: 5,
    monthlyCredits: 4000,
    description: "For growing businesses that need more AI staff and more credits.",
    features: [
      "5 AI staff",
      "4,000 AI credits/month",
      "WhatsApp setup flow",
      "Inbox and leads",
      "Reports",
      "Priority support",
    ],
  },

  business: {
    key: "business",
    name: "Business",
    priceLabel: "Contact Us",
    monthlyPriceUsd: null,
    aiStaffLimit: "custom",
    monthlyCredits: "custom",
    description:
      "For agencies, hotels, clinics, real estate groups, and high-volume teams.",
    features: [
      "10–20 AI staff",
      "Custom AI credits",
      "Multiple business locations",
      "Team access",
      "Custom onboarding",
      "Priority support",
    ],
  },
};

export const kolkapCreditRules: KolkapCreditRule[] = [
  {
    label: "AI customer reply",
    credits: 1,
    description: "A normal customer reply generated by Kolkap AI.",
  },
  {
    label: "AI test message",
    credits: 1,
    description: "A test reply generated before going live.",
  },
  {
    label: "Social media caption",
    credits: 1,
    description: "A simple caption for Instagram, Facebook, TikTok, or LinkedIn.",
  },
  {
    label: "Sales follow-up message",
    credits: 1,
    description: "A short follow-up message for a lead or customer.",
  },
  {
    label: "Property / service description",
    credits: 3,
    description: "A longer description for a property, product, or service.",
  },
  {
    label: "Long content / campaign pack",
    credits: 5,
    description: "Longer content such as campaigns, scripts, or content packs.",
  },
];

export const kolkapTopUpPackages: KolkapTopUpPackage[] = [
  {
    id: "topup_10",
    priceUsd: 10,
    credits: 150,
  },
  {
    id: "topup_25",
    priceUsd: 25,
    credits: 400,
  },
  {
    id: "topup_50",
    priceUsd: 50,
    credits: 900,
  },
  {
    id: "topup_100",
    priceUsd: 100,
    credits: 2000,
  },
];

export const demoWorkspacePlanStatus: KolkapWorkspacePlanStatus = {
  businessName: "Demo Business",
  planKey: "free_trial",
  planName: kolkapPlans.free_trial.name,
  status: "trial",
  trialDaysRemaining: 14,
  creditsTotal: 100,
  creditsUsed: 30,
  creditsRemaining: 70,
  aiStaffLimit: 1,
  aiStaffUsed: 1,
  whatsappStatus: "not_connected",
  goLiveStatus: "draft",
};

export function getKolkapPlan(planKey: KolkapPlanKey) {
  return kolkapPlans[planKey];
}

export function getCreditUsagePercent(status: KolkapWorkspacePlanStatus) {
  if (status.creditsTotal <= 0) return 0;

  return Math.min(
    100,
    Math.round((status.creditsUsed / status.creditsTotal) * 100)
  );
}

export function getCreditRemainingPercent(status: KolkapWorkspacePlanStatus) {
  if (status.creditsTotal <= 0) return 0;

  return Math.min(
    100,
    Math.round((status.creditsRemaining / status.creditsTotal) * 100)
  );
}

export function canCreateMoreAIStaff(status: KolkapWorkspacePlanStatus) {
  if (status.aiStaffLimit === "custom") return true;

  return status.aiStaffUsed < status.aiStaffLimit;
}

export function getAIStaffLimitLabel(status: KolkapWorkspacePlanStatus) {
  if (status.aiStaffLimit === "custom") return "Custom";

  return `${status.aiStaffUsed}/${status.aiStaffLimit}`;
}

export function getPlanCreditLabel(plan: KolkapPlan) {
  if (plan.monthlyCredits === "custom") return "Custom credits";

  if (plan.key === "free_trial") return `${plan.monthlyCredits} AI credits`;

  return `${plan.monthlyCredits.toLocaleString()} AI credits/month`;
}

export function getPlanAIStaffLabel(plan: KolkapPlan) {
  if (plan.aiStaffLimit === "custom") return "10–20 AI staff";

  return `${plan.aiStaffLimit} AI staff`;
}