"use client";

import Link from "next/link";
import { useState } from "react";
import {
  ArrowLeft,
  ArrowRight,
  Bot,
  CheckCircle2,
  CreditCard,
  FileText,
  MessageCircle,
  ReceiptText,
  ShieldCheck,
  Sparkles,
  WalletCards,
  Zap,
} from "lucide-react";
import { useKolkapLanguage } from "@/app/context/LanguageContext";
import {
  demoWorkspacePlanStatus,
  getCreditUsagePercent,
  getKolkapPlan,
  getPlanAIStaffLabel,
  getPlanCreditLabel,
  kolkapCreditRules,
  kolkapTopUpPackages,
} from "@/lib/kolkapPlan";

const translations = {
  en: {
    badge: "Top Up Credits",
    title: "Buy more AI credits anytime.",
    subtitle:
      "Use AI credits for customer replies, test messages, captions, descriptions, follow-ups, and content generation.",
    back: "Back to Dashboard",
    currentPlan: "Current Plan",
    creditBalance: "Credit Balance",
    creditsRemaining: "Credits Remaining",
    creditsUsed: "Credits Used",
    planAllowance: "Plan Allowance",
    aiStaffLimit: "AI Staff Limit",
    chooseTopUp: "Choose Top Up Package",
    chooseTopUpText:
      "Top up when your monthly credits are low or when your business needs more AI replies and content.",
    selected: "Selected",
    buyCredits: "Buy Credits",
    paymentPreview: "Payment Preview",
    paymentText:
      "After payment is connected, this section will show the selected top-up package, payment method, and receipt.",
    creditRules: "How credits are used",
    creditRulesText:
      "Simple AI actions use fewer credits. Longer content uses more credits.",
    billing: "Go to Billing",
    invoices: "Receipt History",
    invoicesText: "Top-up receipts will appear here after purchase.",
    download: "Download",
    secureNote: "Secure credit system",
    secureText:
      "Credits are added to your workspace after successful payment and can be used across your active Kolkap AI staff.",
    statuses: {
      trial: "Trial",
      active: "Active",
      past_due: "Past Due",
      cancelled: "Cancelled",
    },
    ruleLabels: [
      "AI customer reply",
      "AI test message",
      "Social media caption",
      "Sales follow-up message",
      "Property / service description",
      "Long content / campaign pack",
    ],
    ruleDescriptions: [
      "A normal customer reply generated by Kolkap AI.",
      "A test reply generated before going live.",
      "A simple caption for Instagram, Facebook, TikTok, or LinkedIn.",
      "A short follow-up message for a lead or customer.",
      "A longer description for a property, product, or service.",
      "Longer content such as campaigns, scripts, or content packs.",
    ],
    receipts: [
      ["Trial credits added", "100 credits", "$0.00", "Today"],
      ["Top-up purchase", "Pending", "After payment", "Pending"],
    ],
  },

  id: {
    badge: "Top Up Credits",
    title: "Beli AI credits tambahan kapan saja.",
    subtitle:
      "Gunakan AI credits untuk balasan pelanggan, pesan tes, caption, deskripsi, follow-up, dan pembuatan konten.",
    back: "Kembali ke Dashboard",
    currentPlan: "Paket Saat Ini",
    creditBalance: "Saldo Credits",
    creditsRemaining: "Credits Tersisa",
    creditsUsed: "Credits Terpakai",
    planAllowance: "Allowance Paket",
    aiStaffLimit: "Limit AI Staff",
    chooseTopUp: "Pilih Paket Top Up",
    chooseTopUpText:
      "Top up saat credits bulanan hampir habis atau saat bisnis Anda butuh lebih banyak balasan AI dan konten.",
    selected: "Dipilih",
    buyCredits: "Beli Credits",
    paymentPreview: "Preview Pembayaran",
    paymentText:
      "Setelah payment terhubung, bagian ini akan menampilkan paket top-up, metode pembayaran, dan receipt.",
    creditRules: "Cara credits digunakan",
    creditRulesText:
      "Aksi AI sederhana memakai lebih sedikit credits. Konten panjang memakai lebih banyak credits.",
    billing: "Ke Billing",
    invoices: "Riwayat Receipt",
    invoicesText: "Receipt top-up akan muncul di sini setelah pembelian.",
    download: "Download",
    secureNote: "Sistem credits aman",
    secureText:
      "Credits akan ditambahkan ke workspace setelah pembayaran berhasil dan bisa digunakan oleh AI staff Kolkap yang aktif.",
    statuses: {
      trial: "Trial",
      active: "Aktif",
      past_due: "Tertunda",
      cancelled: "Dibatalkan",
    },
    ruleLabels: [
      "Balasan AI pelanggan",
      "Pesan tes AI",
      "Caption social media",
      "Pesan sales follow-up",
      "Deskripsi properti / layanan",
      "Konten panjang / campaign pack",
    ],
    ruleDescriptions: [
      "Balasan pelanggan normal yang dibuat oleh Kolkap AI.",
      "Balasan tes sebelum AI diaktifkan.",
      "Caption sederhana untuk Instagram, Facebook, TikTok, atau LinkedIn.",
      "Pesan follow-up singkat untuk lead atau pelanggan.",
      "Deskripsi lebih panjang untuk properti, produk, atau layanan.",
      "Konten lebih panjang seperti campaign, script, atau content pack.",
    ],
    receipts: [
      ["Trial credits ditambahkan", "100 credits", "$0.00", "Hari ini"],
      ["Pembelian top-up", "Pending", "Setelah payment", "Pending"],
    ],
  },

  zh: {
    badge: "充值 Credits",
    title: "随时购买更多 AI credits。",
    subtitle:
      "AI credits 可用于客户回复、测试消息、社交媒体标题、描述、跟进消息和内容生成。",
    back: "返回仪表板",
    currentPlan: "当前方案",
    creditBalance: "Credits 余额",
    creditsRemaining: "剩余 Credits",
    creditsUsed: "已用 Credits",
    planAllowance: "方案额度",
    aiStaffLimit: "AI 员工限制",
    chooseTopUp: "选择充值套餐",
    chooseTopUpText:
      "当每月 credits 不足，或企业需要更多 AI 回复和内容生成时，可以充值。",
    selected: "已选择",
    buyCredits: "购买 Credits",
    paymentPreview: "付款预览",
    paymentText:
      "付款连接后，这里会显示所选充值套餐、付款方式和收据。",
    creditRules: "Credits 使用方式",
    creditRulesText: "简单 AI 操作使用较少 credits，较长内容使用更多 credits。",
    billing: "前往账单",
    invoices: "收据记录",
    invoicesText: "购买 top-up 后，收据会显示在这里。",
    download: "下载",
    secureNote: "安全 Credits 系统",
    secureText:
      "付款成功后，credits 会添加到您的 workspace，并可用于已启用的 Kolkap AI 员工。",
    statuses: {
      trial: "试用中",
      active: "有效",
      past_due: "逾期",
      cancelled: "已取消",
    },
    ruleLabels: [
      "AI 客户回复",
      "AI 测试消息",
      "社交媒体标题",
      "销售跟进消息",
      "房产 / 服务描述",
      "长内容 / 活动方案",
    ],
    ruleDescriptions: [
      "由 Kolkap AI 生成的普通客户回复。",
      "上线前生成的测试回复。",
      "用于 Instagram、Facebook、TikTok 或 LinkedIn 的简单标题。",
      "给潜在客户或客户的简短跟进消息。",
      "用于房产、产品或服务的较长描述。",
      "较长内容，例如活动方案、脚本或内容组合。",
    ],
    receipts: [
      ["试用 credits 已添加", "100 credits", "$0.00", "今天"],
      ["Top-up 购买", "Pending", "付款后", "Pending"],
    ],
  },

  ms: {
    badge: "Top Up Credits",
    title: "Beli AI credits tambahan bila-bila masa.",
    subtitle:
      "Gunakan AI credits untuk balasan pelanggan, mesej ujian, caption, deskripsi, follow-up, dan penjanaan kandungan.",
    back: "Kembali ke Dashboard",
    currentPlan: "Pakej Semasa",
    creditBalance: "Baki Credits",
    creditsRemaining: "Credits Berbaki",
    creditsUsed: "Credits Digunakan",
    planAllowance: "Allowance Pakej",
    aiStaffLimit: "Limit AI Staff",
    chooseTopUp: "Pilih Pakej Top Up",
    chooseTopUpText:
      "Top up apabila credits bulanan hampir habis atau apabila bisnes anda perlukan lebih banyak balasan AI dan kandungan.",
    selected: "Dipilih",
    buyCredits: "Beli Credits",
    paymentPreview: "Preview Pembayaran",
    paymentText:
      "Selepas payment disambungkan, bahagian ini akan memaparkan pakej top-up, kaedah pembayaran, dan receipt.",
    creditRules: "Cara credits digunakan",
    creditRulesText:
      "Tindakan AI mudah menggunakan kurang credits. Kandungan panjang menggunakan lebih banyak credits.",
    billing: "Ke Billing",
    invoices: "Sejarah Receipt",
    invoicesText: "Receipt top-up akan muncul di sini selepas pembelian.",
    download: "Download",
    secureNote: "Sistem credits selamat",
    secureText:
      "Credits akan ditambah ke workspace selepas pembayaran berjaya dan boleh digunakan oleh AI staff Kolkap yang aktif.",
    statuses: {
      trial: "Trial",
      active: "Aktif",
      past_due: "Tertunda",
      cancelled: "Dibatalkan",
    },
    ruleLabels: [
      "Balasan AI pelanggan",
      "Mesej ujian AI",
      "Caption social media",
      "Mesej sales follow-up",
      "Deskripsi properti / servis",
      "Kandungan panjang / campaign pack",
    ],
    ruleDescriptions: [
      "Balasan pelanggan normal yang dibuat oleh Kolkap AI.",
      "Balasan ujian sebelum AI diaktifkan.",
      "Caption mudah untuk Instagram, Facebook, TikTok, atau LinkedIn.",
      "Mesej follow-up ringkas untuk lead atau pelanggan.",
      "Deskripsi lebih panjang untuk properti, produk, atau servis.",
      "Kandungan lebih panjang seperti campaign, skrip, atau content pack.",
    ],
    receipts: [
      ["Trial credits ditambah", "100 credits", "$0.00", "Hari ini"],
      ["Pembelian top-up", "Pending", "Selepas payment", "Pending"],
    ],
  },
};

export default function TopUpPage() {
  const { language } = useKolkapLanguage();
  const t = translations[language] || translations.en;

  const workspace = demoWorkspacePlanStatus;
  const currentPlan = getKolkapPlan(workspace.planKey);
  const creditUsagePercent = getCreditUsagePercent(workspace);
  const [selectedTopUpId, setSelectedTopUpId] = useState("topup_25");

  const selectedTopUp =
    kolkapTopUpPackages.find((item) => item.id === selectedTopUpId) ||
    kolkapTopUpPackages[1];

  return (
    <main className="bg-[#F7F9FA] text-[#07111F]">
      <section className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:px-8 lg:py-14">
        <div className="mb-8 rounded-[2.2rem] bg-[#07111F] p-7 text-white shadow-2xl shadow-slate-900/20 sm:p-9 lg:p-10">
          <Link
            href="/dashboard"
            className="mb-7 inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-lg font-black text-white transition hover:bg-white/10"
          >
            <ArrowLeft className="h-5 w-5" />
            {t.back}
          </Link>

          <div className="mb-7 inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-lg font-black text-[#7CFF3D]">
            <Sparkles className="h-5 w-5" />
            {t.badge}
          </div>

          <h1 className="max-w-4xl text-4xl font-black leading-tight tracking-[-0.05em] sm:text-5xl lg:text-6xl">
            {t.title}
          </h1>

          <p className="mt-6 max-w-3xl text-xl font-semibold leading-9 text-slate-300">
            {t.subtitle}
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1fr_0.85fr]">
          <section className="rounded-[2.2rem] border border-slate-200 bg-white p-6 shadow-sm shadow-slate-900/5 sm:p-8">
            <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#07111F] text-[#7CFF3D]">
              <WalletCards className="h-8 w-8" />
            </div>

            <p className="text-lg font-black uppercase tracking-[0.18em] text-blue-600">
              {t.creditBalance}
            </p>

            <h2 className="mt-2 text-5xl font-black tracking-[-0.06em]">
              {workspace.creditsRemaining}
            </h2>

            <p className="mt-4 text-xl font-semibold leading-9 text-slate-600">
              {t.creditsRemaining} • {currentPlan.name}
            </p>

            <div className="mt-7 rounded-3xl border border-slate-200 bg-[#F7F9FA] p-5">
              <div className="mb-3 flex items-center justify-between gap-4 text-base font-black text-slate-600">
                <span>{t.creditsUsed}</span>
                <span>
                  {workspace.creditsUsed}/{workspace.creditsTotal}
                </span>
              </div>

              <div className="h-4 overflow-hidden rounded-full bg-white">
                <div
                  className="h-full rounded-full bg-[#7CFF3D]"
                  style={{ width: `${creditUsagePercent}%` }}
                />
              </div>

              <div className="mt-3 flex items-center justify-between text-sm font-black text-slate-500">
                <span>
                  {t.creditsUsed}: {workspace.creditsUsed}
                </span>
                <span>
                  {t.creditsRemaining}: {workspace.creditsRemaining}
                </span>
              </div>
            </div>

            <div className="mt-7 grid gap-4 sm:grid-cols-3">
              <div className="rounded-3xl border border-slate-200 bg-[#F7F9FA] p-5">
                <p className="text-sm font-black uppercase tracking-[0.14em] text-slate-500">
                  {t.currentPlan}
                </p>
                <p className="mt-2 text-2xl font-black">{currentPlan.name}</p>
              </div>

              <div className="rounded-3xl border border-slate-200 bg-[#F7F9FA] p-5">
                <p className="text-sm font-black uppercase tracking-[0.14em] text-slate-500">
                  {t.planAllowance}
                </p>
                <p className="mt-2 text-2xl font-black">
                  {getPlanCreditLabel(currentPlan)}
                </p>
              </div>

              <div className="rounded-3xl border border-slate-200 bg-[#F7F9FA] p-5">
                <p className="text-sm font-black uppercase tracking-[0.14em] text-slate-500">
                  {t.aiStaffLimit}
                </p>
                <p className="mt-2 text-2xl font-black">
                  {getPlanAIStaffLabel(currentPlan)}
                </p>
              </div>
            </div>
          </section>

          <section className="rounded-[2.2rem] border border-blue-100 bg-blue-50 p-6 shadow-sm shadow-blue-900/5 sm:p-8">
            <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#07111F] text-[#7CFF3D]">
              <ShieldCheck className="h-8 w-8" />
            </div>

            <p className="text-lg font-black uppercase tracking-[0.18em] text-blue-700">
              {t.secureNote}
            </p>

            <h2 className="mt-3 text-4xl font-black leading-tight tracking-[-0.05em] text-blue-950">
              {t.secureText}
            </h2>

            <Link
              href="/dashboard/billing"
              className="mt-8 inline-flex w-full items-center justify-center gap-3 rounded-full bg-[#07111F] px-8 py-5 text-xl font-black text-white"
            >
              {t.billing}
              <ArrowRight className="h-6 w-6" />
            </Link>
          </section>
        </div>

        <section className="mt-8 rounded-[2.2rem] border border-slate-200 bg-white p-6 shadow-sm shadow-slate-900/5 sm:p-8">
          <div className="mb-7">
            <p className="text-lg font-black uppercase tracking-[0.18em] text-blue-600">
              {t.chooseTopUp}
            </p>
            <h2 className="mt-2 max-w-4xl text-4xl font-black tracking-[-0.05em]">
              {t.chooseTopUpText}
            </h2>
          </div>

          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {kolkapTopUpPackages.map((item) => {
              const isSelected = selectedTopUpId === item.id;

              return (
                <button
                  key={item.id}
                  type="button"
                  onClick={() => setSelectedTopUpId(item.id)}
                  className={`rounded-[2rem] border p-6 text-left transition hover:-translate-y-1 ${
                    isSelected
                      ? "border-[#07111F] bg-[#07111F] text-white shadow-2xl shadow-slate-900/20"
                      : "border-slate-200 bg-[#F7F9FA] text-[#07111F] hover:border-blue-400 hover:bg-white"
                  }`}
                >
                  <div
                    className={`mb-6 flex h-14 w-14 items-center justify-center rounded-2xl ${
                      isSelected
                        ? "bg-white text-[#07111F]"
                        : "bg-[#07111F] text-[#7CFF3D]"
                    }`}
                  >
                    <Zap className="h-7 w-7" />
                  </div>

                  <p className="text-5xl font-black tracking-[-0.06em]">
                    ${item.priceUsd}
                  </p>

                  <p
                    className={`mt-4 text-2xl font-black ${
                      isSelected ? "text-[#7CFF3D]" : "text-blue-600"
                    }`}
                  >
                    {item.credits.toLocaleString()} AI credits
                  </p>

                  {isSelected ? (
                    <div className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#7CFF3D] px-4 py-2 text-sm font-black text-[#07111F]">
                      <CheckCircle2 className="h-4 w-4" />
                      {t.selected}
                    </div>
                  ) : null}
                </button>
              );
            })}
          </div>
        </section>

        <div className="mt-8 grid gap-6 lg:grid-cols-[0.95fr_1.05fr]">
          <section className="rounded-[2.2rem] bg-[#07111F] p-7 text-white shadow-2xl shadow-slate-900/20 sm:p-8">
            <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#7CFF3D] text-[#07111F]">
              <CreditCard className="h-8 w-8" />
            </div>

            <p className="text-lg font-black uppercase tracking-[0.18em] text-[#7CFF3D]">
              {t.paymentPreview}
            </p>

            <h2 className="mt-3 text-4xl font-black leading-tight tracking-[-0.05em]">
              ${selectedTopUp.priceUsd} •{" "}
              {selectedTopUp.credits.toLocaleString()} AI credits
            </h2>

            <p className="mt-5 text-xl font-semibold leading-9 text-slate-300">
              {t.paymentText}
            </p>

            <button className="mt-8 inline-flex w-full items-center justify-center gap-3 rounded-full bg-[#7CFF3D] px-8 py-5 text-xl font-black text-[#07111F]">
              <CreditCard className="h-6 w-6" />
              {t.buyCredits}
            </button>
          </section>

          <section className="rounded-[2.2rem] border border-slate-200 bg-white p-6 shadow-sm shadow-slate-900/5 sm:p-8">
            <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#07111F] text-[#7CFF3D]">
              <Bot className="h-8 w-8" />
            </div>

            <p className="text-lg font-black uppercase tracking-[0.18em] text-blue-600">
              {t.creditRules}
            </p>

            <h2 className="mt-2 text-4xl font-black tracking-[-0.05em]">
              {t.creditRulesText}
            </h2>

            <div className="mt-7 grid gap-3">
              {kolkapCreditRules.map((rule, index) => (
                <div
                  key={`${rule.label}-${rule.credits}-${index}`}
                  className="grid gap-4 rounded-3xl border border-slate-200 bg-[#F7F9FA] p-5 sm:grid-cols-[1fr_auto]"
                >
                  <div className="flex items-start gap-4">
                    <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-[#07111F]">
                      {rule.credits === 1 ? (
                        <MessageCircle className="h-6 w-6" />
                      ) : (
                        <FileText className="h-6 w-6" />
                      )}
                    </div>

                    <div>
                      <p className="text-lg font-black">
                        {t.ruleLabels[index]}
                      </p>
                      <p className="mt-1 text-base font-semibold leading-7 text-slate-600">
                        {t.ruleDescriptions[index]}
                      </p>
                    </div>
                  </div>

                  <span className="inline-flex items-center justify-center rounded-full bg-white px-5 py-3 text-base font-black text-[#07111F]">
                    {rule.credits} credit{rule.credits > 1 ? "s" : ""}
                  </span>
                </div>
              ))}
            </div>
          </section>
        </div>

        <section className="mt-8 rounded-[2.2rem] border border-slate-200 bg-white p-6 shadow-sm shadow-slate-900/5 sm:p-8">
          <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#07111F] text-[#7CFF3D]">
            <ReceiptText className="h-8 w-8" />
          </div>

          <p className="text-lg font-black uppercase tracking-[0.18em] text-blue-600">
            {t.invoices}
          </p>

          <h2 className="mt-2 text-4xl font-black tracking-[-0.05em]">
            {t.invoicesText}
          </h2>

          <div className="mt-7 grid gap-3">
            {t.receipts.map(([name, credits, amount, date]) => (
              <div
                key={`${name}-${credits}-${date}`}
                className="grid gap-4 rounded-3xl border border-slate-200 bg-[#F7F9FA] p-5 sm:grid-cols-[1fr_auto_auto]"
              >
                <div className="flex items-center gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-[#07111F]">
                    <ReceiptText className="h-6 w-6" />
                  </div>
                  <div>
                    <p className="text-lg font-black">{name}</p>
                    <p className="text-base font-semibold text-slate-500">
                      {credits}
                    </p>
                  </div>
                </div>

                <p className="text-lg font-black">{amount}</p>

                <button className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-black text-[#07111F]">
                  {date === "Pending" ? date : t.download}
                </button>
              </div>
            ))}
          </div>
        </section>
      </section>
    </main>
  );
}